name: uploadToQiNiu

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: ap-southeast-1
          bucket: ${{ secrets.QINIU_BUCKET }}
          exclude: .git,.github
          dist: "./"
          saveroot: PicRepo
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}