name: uploadToQiNiu

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: ap-southeast-1
          bucket: ${{ secrets.QINIU_BUCKET }}
          exclude: .git,.github
          dist: "2021-11-28 12-33-42"
          saveroot: PicRepo
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}